### ISSUE TITLE
erors operation

### ISSUE THREAD

**Issue by panikajo** [javach/VK-Autopost-Bot#1]
C:\VK-Autopost-Bot>main.py
Traceback (most recent call last):
  File "C:\VK-Autopost-Bot\main.py", line 3, in <module>
    from operations import *
  File "C:\VK-Autopost-Bot\operations.py", line 6, in <module>
    from telegram.files.inputmediaphoto import *
ModuleNotFoundError: No module named 'telegram.files'

**Comment by javach** [comment]
pip3 install python-telegram-bot -U
